services:
  - type: web
    name: client-side-image-compressor
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
